apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        echo "Cleaning workspace"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-tests
spec:
  steps:
    - name: nose-test
      image: python:3.11
      script: |
        pip install pytest
        pytest
